/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import AppPackage.AnimationClass;
import BD.Conexion;
import Empleado.EmpleadoBean;
import com.digitalpersona.onetouch.DPFPGlobal;
import com.digitalpersona.onetouch.DPFPTemplate;
import com.digitalpersona.onetouch.verification.DPFPVerificationResult;
import java.awt.event.ActionListener;
import java.io.ByteArrayInputStream;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Document;

/**
 *
 * @author Isaac
 */
public class AltaDestinos extends javax.swing.JFrame {
    
    private UIManager.LookAndFeelInfo apariencias[];

  private DefaultTableModel modelo = new DefaultTableModel();
    
    public AltaDestinos() {
        initComponents();
        
        
        
        
        cambioIdioma("Espanol");
   
        setLocationRelativeTo(null);
        this.setLocationRelativeTo(null);
       try {
           
            modelo.addColumn("Matricula");
            modelo.addColumn("Nombre");
            modelo.addColumn("Apellido Paterno");
            modelo.addColumn("Apellido Materno");
            modelo.addColumn("Carrera");
            modelo.addColumn("Cuatrimestre");
            modelo.addColumn("Grupo");
            modelo.addColumn("Correo Electronico");

            
        } catch (Exception e) {
            e.printStackTrace();  
    }
        
        //txtAMaterno.getDocument().addDocumentListener(documentListener);  
        txtId.setVisible(false);
    }  
    
    public void EliminarRegistro(){
        Connection con= null;
        PreparedStatement stmt = null;
        ResultSet rs = null;
        EmpleadoBean empleado= null;
        try{
            con= Conexion.getConexion();
            stmt.setInt(1, Integer.parseInt(txtId.getText()));
            System.out.println(txtId);
        EliminarRegistro();{
        stmt = con.prepareStatement("DELETE FROM empleado WHERE clave=?");
        
         }
                 int res=stmt.executeUpdate();
                 
                //con.close();
            
        } catch(Exception e){
            System.err.println(e);
        }
    }
    
    
    public void LimpiarCajas(){
      txtClave.setText(null);
      txtAPaterno.setText(null);
      txtAMaterno.setText(null);
      txtNombre.setText(null);
      cbCarrera.setSelectedItem(null);
      cbCuatri.setSelectedItem(null);
      cbGrupo.setSelectedItem(null);
      
  } 
    
    
    public void cambioIdioma(String nombreIdioma){
        
        idioma=new Idioma(nombreIdioma);
        
        
        btnCambio.setText(idioma.getProperty("cambio"));
        jBuscar.setText(idioma.getProperty("matricula"));
        LblCarrera.setText(idioma.getProperty("carrera"));
        LblCuatri.setText(idioma.getProperty("cuatrimestre"));
        LblGrupo.setText(idioma.getProperty("grupo"));
        LblName.setText(idioma.getProperty("nombre"));
        LblApp.setText(idioma.getProperty("apellidoP"));
        LblApm.setText(idioma.getProperty("apellidoM"));
        LblConsulta.setText(idioma.getProperty("consulta"));
        btnModificar.setText(idioma.getProperty("modificar"));
        btnBorrar.setText(idioma.getProperty("eliminar"));

        
        cbIdiomas.removeAllItems();
        
        
        
        
        
        String idiomas[]={
                          idioma.getProperty("espanol"),
                          idioma.getProperty("ingles"),
                          
                          };
        
        for(int i=0;i<idiomas.length;i++){
            cbIdiomas.addItem(idiomas[i]);
        }
        }
BD.ConexionBD metodo= new BD.ConexionBD();


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LblConsulta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbIdiomas = new javax.swing.JComboBox<>();
        btnCambio = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        LblName = new javax.swing.JLabel();
        LblApp = new javax.swing.JLabel();
        LblApm = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtAPaterno = new javax.swing.JTextField();
        txtClave = new javax.swing.JTextField();
        jBuscar = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtAMaterno = new javax.swing.JTextField();
        LblCarrera = new javax.swing.JLabel();
        LblGrupo = new javax.swing.JLabel();
        LblCuatri = new javax.swing.JLabel();
        btnBorrar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        cbCarrera = new javax.swing.JComboBox<>();
        cbCuatri = new javax.swing.JComboBox<>();
        cbGrupo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtAlumnos = new javax.swing.JTable();
        btnCarTab = new javax.swing.JButton();
        txtCampo = new javax.swing.JTextField();

        jButton2.setText("jButton2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblConsulta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblConsulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblConsulta.setText("Consulta de Estudiante");
        jPanel2.add(LblConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Multiply_32px.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, -1, -1));

        cbIdiomas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbIdiomasItemStateChanged(evt);
            }
        });
        cbIdiomas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIdiomasActionPerformed(evt);
            }
        });
        jPanel2.add(cbIdiomas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));

        btnCambio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Globe_32px.png"))); // NOI18N
        btnCambio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCambio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCambioMouseClicked(evt);
            }
        });
        jPanel2.add(btnCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1110, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblName.setFont(new java.awt.Font("Keep Calm Med", 0, 11)); // NOI18N
        LblName.setText("Nombre");
        jPanel3.add(LblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        LblApp.setFont(new java.awt.Font("Keep Calm Med", 0, 11)); // NOI18N
        LblApp.setText("Apellido Paterno");
        jPanel3.add(LblApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        LblApm.setFont(new java.awt.Font("Keep Calm Med", 0, 11)); // NOI18N
        LblApm.setText("Apellido Materno");
        jPanel3.add(LblApm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        jPanel3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 290, -1));
        jPanel3.add(txtAPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 290, -1));

        txtClave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtClaveMouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtClaveMouseReleased(evt);
            }
        });
        txtClave.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtClaveInputMethodTextChanged(evt);
            }
        });
        txtClave.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtClavePropertyChange(evt);
            }
        });
        txtClave.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                txtClaveVetoableChange(evt);
            }
        });
        jPanel3.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 290, -1));

        jBuscar.setFont(new java.awt.Font("Perpetua Titling MT", 3, 12)); // NOI18N
        jBuscar.setText("MATRICULA");
        jPanel3.add(jBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, 40));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Search_32px_2.png"))); // NOI18N
        btnBuscar.setBorder(null);
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setFocusPainted(false);
        btnBuscar.setFocusable(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        txtAMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAMaternoActionPerformed(evt);
            }
        });
        jPanel3.add(txtAMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 290, -1));

        LblCarrera.setFont(new java.awt.Font("Keep Calm Med", 0, 11)); // NOI18N
        LblCarrera.setText("Carrera:");
        jPanel3.add(LblCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        LblGrupo.setFont(new java.awt.Font("Keep Calm Med", 0, 11)); // NOI18N
        LblGrupo.setText("Grupo:");
        jPanel3.add(LblGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        LblCuatri.setFont(new java.awt.Font("Keep Calm Med", 0, 11)); // NOI18N
        LblCuatri.setText("Cuatrimestre:");
        jPanel3.add(LblCuatri, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        btnBorrar.setBackground(new java.awt.Color(255, 102, 102));
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_cancel.png"))); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.setBorder(null);
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 90, -1));

        txtId.setEnabled(false);
        jPanel3.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 60, -1));

        btnModificar.setBackground(new java.awt.Color(0, 153, 0));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/revert.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setBorder(null);
        btnModificar.setFocusCycleRoot(true);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel3.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 100, -1));

        cbCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "TSU En mantenimiento Area Industrial", "TSU En Mecatronica Area Automatizacion", "TSU En Tecnologias de la informacion Area desarrollo de software multiplataforma", "TSU En Quimica Area Industrial", "TSU En Contaduria ", "TSU En Administracion Area Capital Humano", "TSU En Mecanica Area Automotriz", "TSU En Energias Renovables Area Ahorro y calidad", "ING Mantenimiento Industrial", "ING Mecatronica", "ING Tecnologias de la Informacion", "ING Quimica", "LIC En Contaduria", "LIC Gestion del Captal Humano", "ING Metal Mecanica", " " }));
        cbCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCarreraActionPerformed(evt);
            }
        });
        jPanel3.add(cbCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 270, -1));

        cbCuatri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Primero", "Segundo", "Tercero", "Cuarto", "Quinto", "Sexto", "Septimo", "Octavo", "Noveno", "Decimo", "Undecimo", " " }));
        jPanel3.add(cbCuatri, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 140, -1));

        cbGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "101", "102", "103", "104", "105", "201", "202", "203", "304", "305", "401", "402", "403", "404", "405", "501", "502", "503", "504", "505", "601", "602", "603", "604", "605", "701", "702", "703", "704", "705", "801", "802", "803", "804", "805", "901", "902", "903", "904", "905", "1001", "1002", "1003", "1004", "1005" }));
        jPanel3.add(cbGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 140, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Next_page_L64px.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, -1, -1));

        jtAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Matricula", "Nombre", "Apellido Paterno", "Apellido Materno", "Carrera", "Cuatrimestre", "Grupo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtAlumnos);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 730, 440));

        btnCarTab.setText("Cargar Datos");
        btnCarTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarTabActionPerformed(evt);
            }
        });
        jPanel3.add(btnCarTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 530, -1, -1));

        txtCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampoActionPerformed(evt);
            }
        });
        txtCampo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCampoKeyTyped(evt);
            }
        });
        jPanel3.add(txtCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 150, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1110, 570));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClavePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtClavePropertyChange
       
      //JOptionPane.showMessageDialog(this, jTextField4.getText());  
        
    }//GEN-LAST:event_txtClavePropertyChange

    private void txtClaveVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_txtClaveVetoableChange
      // JOptionPane.showMessageDialog(this, jTextField4.getText());
    }//GEN-LAST:event_txtClaveVetoableChange

    private void txtClaveInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtClaveInputMethodTextChanged
      // JOptionPane.showMessageDialog(this, jTextField4.getText());
    }//GEN-LAST:event_txtClaveInputMethodTextChanged

    private void txtClaveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtClaveMouseReleased
       //JOptionPane.showMessageDialog(this, jTextField4.getText());
    }//GEN-LAST:event_txtClaveMouseReleased

    private void txtClaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtClaveMouseEntered
       // JOptionPane.showMessageDialog(this, jTextField4.getText());
    }//GEN-LAST:event_txtClaveMouseEntered

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Connection con= null;
        PreparedStatement stmt = null;
        ResultSet rs = null;
        EmpleadoBean empleado= null;
        try{
            con= Conexion.getConexion();
            stmt = con.prepareStatement("SELECT * FROM empleado WHERE clave = ?");
            stmt.setInt(1, Integer.parseInt (txtClave.getText()));
            
            rs = stmt.executeQuery();
            
            if(rs.next()){
               txtId.setText(rs.getString("clave"));
               txtAPaterno.setText(rs.getString("apPaterno"));
               txtAMaterno.setText(rs.getString("apMaterno"));
                txtNombre.setText(rs.getString("nombre"));
               cbCarrera.setSelectedItem(rs.getString("NombreCarrera"));
               cbCuatri.setSelectedItem(rs.getString("NombreCuatrimestre"));
               cbGrupo.setSelectedItem(rs.getString("NombreGrupo"));
            } else{
                JOptionPane.showMessageDialog(null,"No existe ninguna clave vuelva a intentarlo");
                
            }
            
            con.close();
        } catch(Exception e){
            
            System.err.println(e);
            
        }

       
    
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        
        Connection con= null;
        PreparedStatement stmt = null;
        ResultSet rs = null;
        EmpleadoBean empleado= null;
        try{
            con= Conexion.getConexion();
            stmt.setInt(1, Integer.parseInt(txtId.getText()));
            System.out.println(txtId);
        EliminarRegistro();{
        stmt = con.prepareStatement("DELETE FROM empleado WHERE clave=?");
        
         }
                 int res=stmt.executeUpdate();
                 
                con.close();
            
        } catch(Exception e){
            System.err.println(e);
        }
        
        //if(JOptionPane.showConfirmDialog(rootPane, "Se eliminará el registro, ¿desea continuar?",
        //"Eliminar Registro", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)EliminarRegistro();
                    
                

           
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        Connection con= null;
        PreparedStatement stmt = null;
        ResultSet rs = null;
        EmpleadoBean empleado= null;
        try{
            con= Conexion.getConexion();
stmt = con.prepareStatement("UPDATE empleado SET nombre=?, ApPaterno=?, ApMaterno=?, NombreCarrera=?, NombreCuatrimestre=?, NombreGrupo=? WHERE clave=?");
            
                
                stmt.setString(1,txtAPaterno.getText());
                stmt.setString(2,txtAMaterno.getText());    
                stmt.setString(3,txtNombre.getText());              
                stmt.setString(4,cbCarrera.getSelectedItem().toString());
                stmt.setString(5,cbCuatri.getSelectedItem().toString());
                stmt.setString(6,cbGrupo.getSelectedItem().toString());
                stmt.setString(7, txtId.getText());
            
                int res=stmt.executeUpdate();
                
                
                if(res > 0){
                    JOptionPane.showMessageDialog(null, "Estudiante Actualizado");
                } else{
                    JOptionPane.showMessageDialog(null, "Imposible Actualizar");
                }
                con.close();
            LimpiarCajas();
        } catch(Exception e){
            System.err.println(e);
        }       
    }//GEN-LAST:event_btnModificarActionPerformed

    private void cbCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCarreraActionPerformed

    private void txtAMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAMaternoActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
      Login Ventana=new Login();
        Ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnCambioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambioMouseClicked
        switch(cbIdiomas.getSelectedIndex()){
            
           
           
            case 0:
                cambioIdioma("Espanol");
                break;
            case 1:
                cambioIdioma("Ingles");
                break;
            

        }
    }//GEN-LAST:event_btnCambioMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
        int result = JOptionPane.showConfirmDialog(null, "Desea salir de la captura de datos","Exit",JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        if(result == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       this.setState(CapturaDatos.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnCarTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarTabActionPerformed
        try{
            DefaultTableModel modelo = new DefaultTableModel();
            jtAlumnos.setModel(modelo);
            
            PreparedStatement ps = null;
            ResultSet rs = null;
            
            Conexion conn = new Conexion();
            Connection con = conn.getConexion();
            
            String sql = "select clave,Nombre, ApPaterno, ApMaterno, NombreCarrera, NombreCuatrimestre, NombreGrupo from empleado";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
             
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
            
            modelo.addColumn("Matricula");
            modelo.addColumn("Nombre");
            modelo.addColumn("Apellido Paterno");
            modelo.addColumn("Apellido Materno");
            modelo.addColumn("Carrera");
            modelo.addColumn("Cuatrimestre");
            modelo.addColumn("Grupo");
            
            while(rs.next()){
                Object[] filas = new  Object[cantidadColumnas];
                
                for(int i = 0; i<cantidadColumnas; i++){
                    filas[i] = rs.getObject(i+1);
                }
                modelo.addRow(filas);
            }
        }catch(SQLException ex){
            System.err.println(ex.toString());
        }
    }//GEN-LAST:event_btnCarTabActionPerformed

    private void cbIdiomasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIdiomasActionPerformed
       
    }//GEN-LAST:event_cbIdiomasActionPerformed

    private void txtCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampoActionPerformed

    private void txtCampoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCampoKeyTyped
       
    }//GEN-LAST:event_txtCampoKeyTyped

    private void cbIdiomasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbIdiomasItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbIdiomasItemStateChanged

//    DocumentListener documentListener = new DocumentListener() {
//      public void changedUpdate(DocumentEvent documentEvent) {
//        printIt(documentEvent);
//      }
//      public void insertUpdate(DocumentEvent documentEvent) {
//        printIt(documentEvent);
//      }
//      public void removeUpdate(DocumentEvent documentEvent) {
//        printIt(documentEvent);
//      }
//      private void printIt(DocumentEvent documentEvent) {
//        DocumentEvent.EventType type = documentEvent.getType();
//        String typeString = null;
//        if (type.equals(DocumentEvent.EventType.CHANGE)) {
//          typeString = "Change";
//        }  else if (type.equals(DocumentEvent.EventType.INSERT)|| type.equals(DocumentEvent.EventType.REMOVE)) {
//          //typeString = "Insert";
//            txtClave.setText(txtAMaterno.getText());
//          
//        }  
//       
//      }
//    };
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaDestinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaDestinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaDestinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaDestinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaDestinos().setVisible(true);
            }
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblApm;
    private javax.swing.JLabel LblApp;
    private javax.swing.JLabel LblCarrera;
    private javax.swing.JLabel LblConsulta;
    private javax.swing.JLabel LblCuatri;
    private javax.swing.JLabel LblGrupo;
    private javax.swing.JLabel LblName;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel btnCambio;
    private javax.swing.JButton btnCarTab;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cbCarrera;
    private javax.swing.JComboBox<String> cbCuatri;
    private javax.swing.JComboBox<String> cbGrupo;
    private javax.swing.JComboBox<String> cbIdiomas;
    private javax.swing.JLabel jBuscar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jtAlumnos;
    private javax.swing.JTextField txtAMaterno;
    private javax.swing.JTextField txtAPaterno;
    private javax.swing.JTextField txtCampo;
    public javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
private Idioma idioma;
}
